function boxplottingSimKernelResults(nn,rbfSvm,rf,ckSvm,linSvm,ckRf,ckNn,classificationBoolean)
nnResult = cat(1,nn(:).perfMetric); 
rbfResult = cat(1,rbfSvm(:).perfMetric);
rfResult = cat(1,rf(:).perfMetric);
ckSvmResult = cat(1,ckSvm(:).perfMetric);
% linResult = cat(1,nn(:).perfMetric); %%%%%%%%%%%%
linResult = cat(1,linSvm(:).perfMetric); %%%%%%%%%%%%
ckRfResult = cat(1,ckRf(:).perfMetric);
ckNnResult = cat(1,ckNn(:).perfMetric);

% compute equal spacing between algorithm bars within a subsampling
% iteration
x = linspace(0,1,9);
    
clf
hold on
grid on
boxplot([nnResult linResult rbfResult rfResult ckSvmResult ckRfResult ckNnResult],...
    'PlotStyle','compact',...
    'FactorSeparator',1,...
    'position',...
    [1:5 ...
    x(2)+(1:5)...
    x(3)+(1:5) ...
    x(4)+(1:5) ...
    x(5)+(1:5),...
    x(6)+(1:5),...
    x(7)+(1:5)],...
    'labels',...
{'nn' 'nn' 'nn' 'nn' 'nn'...
'linSvm' 'linSvm' 'linSvm' 'linSvm' 'linSvm'...
'rbfSvm' 'rbfSvm' 'rbfSvm' 'rbfSvm' 'rbfSvm'...
'rf' 'rf' 'rf' 'rf' 'rf'...
'skSvm' 'skSvm' 'skSvm' 'skSvm' 'skSvm'...
'skRf' 'skRf' 'skRf' 'skRf' 'skRf'...
'skNn' 'skNn' 'skNn' 'skNn' 'skNn'})
xlabel('Subsampling ratio')
if classificationBoolean
    ylabel('Accuracy')
else
    ylabel('R^2')
end
line([1.875 1.875],[-100 100],'Color','k')
line([2.875 2.875],[-100 100],'Color','k')
line([3.875 3.875],[-100 100],'Color','k')
line([4.875 4.875],[-100 100],'Color','k')

end