function boxplottingSimKernelResults(nn,rbfSvm,rf,ckSvm,linSvm,ckRf,ckNn,classificationBoolean)
nnResult = cat(1,nn(:).perfMetric); 
rbfResult = cat(1,rbfSvm(:).perfMetric);
rfResult = cat(1,rf(:).perfMetric);
ckSvmResult = cat(1,ckSvm(:).perfMetric);
% linResult = cat(1,nn(:).perfMetric); %%%%%%%%%%%%
linResult = cat(1,linSvm(:).perfMetric); %%%%%%%%%%%%
ckRfResult = cat(1,ckRf(:).perfMetric);
ckNnResult = cat(1,ckNn(:).perfMetric);

clf
hold on
boxplot([nnResult linResult rbfResult rfResult ckSvmResult ckRfResult ckNnResult],...
    'PlotStyle','compact',...
    'position',...
    [1:5 ...
    1.1:5.1 ...
    1.2:5.2 ...
    1.3:5.3 ...
    1.4:5.4,...
    1.5:5.5,...
    1.6:5.6],...
    'labels',...
{'nn' 'nn' 'nn' 'nn' 'nn'...
'linSvm' 'linSvm' 'linSvm' 'linSvm' 'linSvm'...
'rbfSvm' 'rbfSvm' 'rbfSvm' 'rbfSvm' 'rbfSvm'...
'rf' 'rf' 'rf' 'rf' 'rf'...
'skSvm' 'skSvm' 'skSvm' 'skSvm' 'skSvm'...
'skRf' 'skRf' 'skRf' 'skRf' 'skRf'...
'skNn' 'skNn' 'skNn' 'skNn' 'skNn'})
xlabel('Subsampling ratio')
if classificationBoolean
    ylabel('Accuracy')
else
    ylabel('R^2')
end
line([1.7 1.7],[-100 100],'Color','k')
line([2.7 2.7],[-100 100],'Color','k')
line([3.7 3.7],[-100 100],'Color','k')
line([4.7 4.7],[-100 100],'Color','k')

end